
    drop table PERSON if exists;
    drop table SESSION_ if exists;
    create table PERSON (
        ID bigint generated by default as identity (start with 1),
        ADDRESS varchar(100),
        EMAIL varchar(50),
        NAME_ varchar(50),
        VERSION_ bigint,
        CUSTOMERS_SESSION__HJID bigint,
        primary key (ID)
    );
    create table SESSION_ (
        HJID bigint generated by default as identity (start with 1),
        USER_ varchar(255),
        primary key (HJID)
    );
    alter table PERSON 
        add constraint FK8C768F555E88ECA8 
        foreign key (CUSTOMERS_SESSION__HJID) 
        references SESSION_;